export const JOB_POST_REQUEST = "JOB_POST_REQUEST";
export const JOB_POST_SUCCESS = "JOB_POST_SUCCESS";
export const JOB_POST_FAIL= "JOB_POST_FAIL";

export const ALL_JOB_REQUEST = "ALL_JOB_REQUEST";
export const ALL_JOB_SUCCESS = "ALL_JOB_SUCCESS";
export const ALL_JOB_FAIL= "ALL_JOB_FAIL";

export const JOB_DETAIL_REQUEST = "ALL_JOB_REQUEST";
export const JOB_DETAIL_SUCCESS = "ALL_JOB_SUCCESS";
export const JOB_DETAIL_FAIL= "ALL_JOB_FAIL";

export const JOB_APPLY_REQUEST = "JOB_APPLY_REQUEST";
export const JOB_APPLY_SUCCESS = "JOB_APPLY_SUCCESS";
export const JOB_APPLY_FAIL= "JOB_APPLY_FAIL";